### ISSUE TITLE
Installation problem on MacOS

### ISSUE THREAD

**Issue by valgartner** [mdrasmus/argweaver#23]
Hello,

I'm running MacOS Mojave Version 10.14.6. 

I tried installing argweaver using `pip install argweaver` and got the following error message:

```Collecting argweaver
  Using cached argweaver-0.8.1.tar.gz (1.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/vgartner/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/08/wh9lc93s30gcdh_npnfl1fr40000gn/T/pip-install-vaf7hcwp/argweaver/setup.py'"'"'; __file__='"'"'/private/var/folders/08/wh9lc93s30gcdh_npnfl1fr40000gn/T/pip-install-vaf7hcwp/argweaver/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/08/wh9lc93s30gcdh_npnfl1fr40000gn/T/pip-install-vaf7hcwp/argweaver/pip-egg-info
         cwd: /private/var/folders/08/wh9lc93s30gcdh_npnfl1fr40000gn/T/pip-install-vaf7hcwp/argweaver/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/08/wh9lc93s30gcdh_npnfl1fr40000gn/T/pip-install-vaf7hcwp/argweaver/setup.py", line 109
        raise DistutilsSetupError, \
                                 ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I also tried installing using `make` and `make install` and got what appears to be the same error message:

```$ make install prefix=$HOME/local
mkdir -p /Users/vgartner/local/bin
cp bin/arg-sample bin/arg-summarize bin/smc2bed bin/* /Users/vgartner/local/bin
python setup.py install --prefix=/Users/vgartner/local
  File "setup.py", line 109
    raise DistutilsSetupError, \
                             ^
SyntaxError: invalid syntax
make: *** [install] Error 1
```

**Comment by valgartner** [comment]
For posterity, the solution to this problem is simply to use python2 for the installation instead of python3 :) My bad for assuming no one uses python2 any more.
