### ISSUE TITLE
Problem with tutorial

### ISSUE THREAD

**Issue by luishdez35** [mdrasmus/argweaver#25]
Hello, I have an error when trying to follow the tutorial. 

`(base) luiscarloshernandez@MacBook-Air-de-Luis bin % ../bin/arg-sim \`
   ` -k 8 -L 100000 \`
   ` -N 10000 -r 1.6e-8 -m 1.8e-8 \`
    `-o test1/test1`
 ` File "../bin/arg-sim", line 72`
   ` print "model parameters:"`
          ^
`SyntaxError: Missing parentheses in call to 'print'. Did you mean print("model parameters:")?`

Can you help me with that? Maybe I don't install the program correctly.

**Comment by luishdez35** [comment]
I fix the issue by creating an env with python 2.7 but I am still have a error.

`Traceback (most recent call last):`
`  File "../bin/arg-sim", line 7, in <module>`
`    import argweaver`
`ImportError: No module named argweaver`

Thanks

**Comment by luishdez35** [comment]
I solve the problem
Thanks
