### ISSUE TITLE
pip installation of ARGweaver throwing an error

### ISSUE THREAD

**Issue by drdna** [mdrasmus/argweaver#28]
pip install argweaver throws this error
```bash
 $ pip install argweaver
Collecting argweaver
Using cached argweaver-0.8.1.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lp/n33fnct96bn1bf7gbzz2qt3h0000gn/T/pip-install-4kh3u30x/argweaver_4065a4fccc804ec4a163c4aa9487343a/setup.py", line 109
          raise DistutilsSetupError, \
                                   ^
```

**Comment by mmosmond** [comment]
See #23  -- I think you need to use python2 (it worked for me)

**Comment by sdtemple** [comment]
> See #23 -- I think you need to use python2 (it worked for me)

This works for me as well.
